### ISSUE TITLE
[bug] Wi-Fi is now changed to WLAN on new update.

### ISSUE THREAD

**Issue by s-kk** [parrotgeek1/Globalize#6] opened 2020-03-08 10:02 UTC
Hello!
Happy to see new updates on this project.  
However after the update from ```0.2.5``` to ```0.3``` I noticed that the ```WLAN``` preference label is still ```WLAN``` after multiple reboot, reinstallation, and re-```ldrestart```. So, I guess it's a bug caused by new updates.

Platform: iPhone 7 Plus
iOS Version: 13.3
Jailbreak Tool: checkra1n
Expected results: after installation, the original ```WLAN``` should be ```Wi-Fi```
Results I got: after installation, the original ```WLAN``` is still ```WLAN```.  

I didn't notice any other bugs except this.

Thanks for helping!

**Comment by s-kk** [comment] 2020-03-08 10:22
Updates: I've noticed that the ```WLAN``` label would be changed to ```Wi-Fi``` if I simply restart the phone without checkra1n jailbreak.  
After the tethered jailbreak, ```WLAN``` would appear again.

**Comment by parrotgeek1** [comment] 2020-03-08 20:11
Yes it's a bug caused by the new update. I have thought of a way to both fix the issues and retain the Wi-Fi preference label

**Comment by parrotgeek1** [comment] 2020-03-15 04:37
Does this still happen on 0.3.1?

**Comment by parrotgeek1** [comment] 2020-03-15 05:13
fixed in 0.3.2

**Closed by parrotgeek1** 2020-03-15 05:13 UTC
