### ISSUE TITLE
ios14.3 is not supported

### ISSUE THREAD

**Issue by jackiejtr** [parrotgeek1/Globalize#10] opened 2021-04-09 17:28 UTC
Is there any plan to continue update? thx

**Comment by Tintin-404** [comment] 2021-05-25 22:18
I have the same issue

**Comment by Tintin-404** [comment] 2021-05-25 22:41
> Is there any plan to continue update? thx

Hi, I tried to install the deb on iOS 14.3, remember don’t respiring, then ldrestart. It workers. I think you can try this operation.

**Comment by parrotgeek1** [comment] 2021-06-20 19:58
In that case, this issue was caused by user error so I will close it. I'm
glad to hear it's still working. --

Ethan Nelson-Moore

**Closed** 2021-06-20 20:04 UTC
